#!/bin/sh
#
# @name Gazebo x500
#
# @type Quadrotor
#

# . ${R}etc/init.d/rc.mc_defaults
. ${R}etc/init.d/rc.vtol_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=default}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=tailsitter}

param set-default MAV_TYPE 20

param set-default SIM_GZ_EN 1

#  * Board rotation
#  *
#  * This parameter defines the rotation of the FMU board relative to the platform.
#  *
param set-default SENS_BOARD_ROT 24  # pitch rotation 90 deg

# /**
#  * Lock control surfaces in hover
#  *
#  * If set to 1 the control surfaces are locked at the disarmed value in multicopter mode.
#  *
#  * @boolean
#  * @group VTOL Attitude Control
#  */
## TODO low pitch don't use!
param set-default VT_ELEV_MC_LOCK 0  # unlock elevon servo

# simulation gps
param set-default SENS_EN_GPSSIM 1
# simulation barometer
param set-default SENS_EN_BAROSIM 0
# simulation magenetometer
param set-default SENS_EN_MAGSIM 1
# simulation airspeed
param set-default SENS_EN_ARSPDSIM 1

# tailsitter setting to solve airspeed sim
param set-default HILAB_ARSPDROT 1
# bypass the flight checks without airspeed sensor
# param set-default CBRK_AIRSPD_CHK 162128


param set-default SIM_GPS_USED 40  # use 40 satellites

param set-default CA_AIRFRAME 4		# 4：tailsitter
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.13
param set-default CA_ROTOR0_PY 0.22
param set-default CA_ROTOR0_KM  0.05

param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.20
param set-default CA_ROTOR1_KM  0.05

param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.22
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY 0.20
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 2000
param set-default SIM_GZ_EC_MAX2 2000
param set-default SIM_GZ_EC_MAX3 2000
param set-default SIM_GZ_EC_MAX4 2000

# servo roll pitch yaw
param set-default SIM_GZ_SV_FUNC1 201
param set-default SIM_GZ_SV_FUNC2 202
param set-default SIM_GZ_SV_FUNC3 203

# TODO: set 567 max and mini

param set-default MPC_THR_HOVER 0.60

## for simulation due to lift-drag-plugin features; use virtual Elevator
param set-default CA_SV_CS_COUNT 3
param set-default CA_SV_CS0_TYPE 1
#  Control Surface ${i} roll torque scaling
param set-default CA_SV_CS0_TRQ_R -0.8    # Control Surface ${i} roll torque scaling
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS1_TRQ_R 0.8
param set-default CA_SV_CS2_TYPE 3
#  Control Surface ${i} pitch torque scaling
param set-default CA_SV_CS2_TRQ_P 1

## LYU: for real vehicle
# param set-default CA_SV_CS_COUNT 2	# control surface
# param set-default CA_SV_CS0_TYPE 5	# Control Surface ${i} type, 5: Left Elevon;  6: Right Elevon
# param set-default CA_SV_CS0_TRQ_P 0.5   # Control Surface ${i} pitch torque scaling
# param set-default CA_SV_CS0_TRQ_Y -0.5	# Control Surface ${i} yaw torque scaling (fixed wing frame: roll)
# param set-default CA_SV_CS1_TYPE 6
# param set-default CA_SV_CS1_TRQ_P 0.5
# param set-default CA_SV_CS1_TRQ_Y 0.5

# LYU: for real vehicle
# param set-default PWM_MAIN_FUNC1 101
# param set-default PWM_MAIN_FUNC2 102
# param set-default PWM_MAIN_FUNC3 103
# param set-default PWM_MAIN_FUNC4 104
# param set-default PWM_MAIN_FUNC5 0
# param set-default PWM_MAIN_FUNC6 201
# param set-default PWM_MAIN_FUNC7 202
# param set-default PWM_MAIN_REV 96 # invert both elevons

# Single-EKF (for replay)
# param set-default EKF2_MULTI_IMU 0
# param set-default SENS_IMU_MODE 1

## set fixed-wing parameters
# param set-default FW_P_TC 0.6
# param set-default FW_PR_FF 0.1
# param set-default FW_PSP_OFF 2
# param set-default FW_RR_FF 0.1
# param set-default FW_RR_I 0.2
# param set-default FW_RR_P 0.3
# param set-default FW_THR_TRIM 0.35
# param set-default FW_THR_MAX 0.8
# param set-default FW_THR_MIN 0.05
# param set-default FW_T_CLMB_MAX 6
# param set-default FW_T_HRATE_FF 0.5
# param set-default FW_T_SINK_MAX 3
# param set-default FW_T_SINK_MIN 1.6

## set MC param
param set-default MC_AIRMODE 1 		#@value 0 Disabled; value 1 Roll/Pitch; value 2 Roll/Pitch/Yaw
param set-default MPC_VEL_MANUAL 10
param set-default MPC_XY_VEL_MAX 15
param set-default MPC_Z_VEL_MAX_UP 5
param set-default MPC_Z_VEL_MAX_DN 3

## set FW param
param set-default FW_PR_FF 0.2
param set-default FW_PR_P 0.9
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MIN -15
param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3
param set-default FW_THR_TRIM 0.25
param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_T_CLMB_MAX 8
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2
param set-default FW_AIRSPD_TRIM 17

## set transition param
param set-default VT_ARSP_TRANS 10
param set-default VT_B_TRANS_DUR 5
param set-default VT_FW_DIFTHR_EN 0
param set-default VT_FW_DIFTHR_S_Y 0.0
param set-default VT_FW_DIFTHR_S_P 0.0
param set-default VT_FW_DIFTHR_S_R 0.0
param set-default VT_F_TRANS_DUR 5
param set-default VT_TYPE 0

param set-default WV_EN 0

# # 1. 加大 P 值 (增加刚度，锁住姿态)
# param set MC_PITCH_P 0.05
# param set MC_PITCHRATE_P 0.15
# # 2. (可选) 如果还震，稍微给点微分 D 来阻尼
# param set MC_PITCHRATE_D 0.003

# # 3. 再次确认积分项 (防止疯转)
# param set MC_YAWRATE_I 0.01